services:

  jenkins-controller:
    image: jenkins/jenkins:lts-jdk17
    container_name: container-jenkins-controller
    restart: always
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
